from __future__ import annotations

from typing import Any

class Cache:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get(self, key: str, default: Any | None = ...) -> Any: ...
    def set(self, key: str, value: Any, expire: float | None = ...) -> None: ...
    def close(self) -> None: ...

__all__ = ["Cache"]
