from typing import Any

Schema = Any

udf: Any
options: Any
expr: Any

duckdb: Any


def schema(*args: Any, **kwargs: Any) -> Any: ...

def memtable(*args: Any, **kwargs: Any) -> Any: ...

def window(*args: Any, **kwargs: Any) -> Any: ...

def desc(*args: Any, **kwargs: Any) -> Any: ...

def row_number(*args: Any, **kwargs: Any) -> Any: ...

def null() -> Any: ...

def literal(*args: Any, **kwargs: Any) -> Any: ...

def ifelse(*args: Any, **kwargs: Any) -> Any: ...

def read_csv(*args: Any, **kwargs: Any) -> Any: ...

def __getattr__(name: str) -> Any: ...
