from __future__ import annotations

from typing import Any

class Node:
    ...

class SafeLoader:
    def __init__(self, stream: Any) -> None: ...
    @classmethod
    def add_multi_constructor(cls, tag_prefix: str, constructor: Any) -> None: ...

Loader = SafeLoader

def load(stream: Any, Loader: type[SafeLoader] | None = ...) -> Any: ...
def safe_load(stream: Any) -> Any: ...
def dump(data: Any, *args: Any, **kwargs: Any) -> str: ...

def __getattr__(name: str) -> Any: ...

__all__ = ["Node", "SafeLoader", "load", "safe_load", "dump"]
