"""Mocks for writer agent tool execution.

This module simulates the writer agent's tool calls based on fixture data.
Used to create deterministic, repeatable pipeline execution.
"""

from dataclasses import dataclass
from typing import Any


@dataclass
class MockWriterToolCalls:
    """Sequence of tool calls the writer agent makes."""

    post_write: dict  # write_post_tool call
    profile_reads: list[dict]  # read_profile_tool calls
    profile_writes: list[dict]  # write_profile_tool calls
    rag_searches: list[dict]  # search_media_tool calls
    annotations: list[dict]  # annotate_conversation_tool calls
    banners: list[dict]  # generate_banner_tool calls


def get_fixture_tool_sequence() -> MockWriterToolCalls:
    """Return the expected tool call sequence for whatsapp_sample fixture.

    This represents a minimal, realistic sequence of tool calls that
    the writer agent would make during E2E testing.
    """
    return MockWriterToolCalls(
        post_write={
            "metadata": {
                "title": "Test Pipeline Output",
                "slug": "test-pipeline-output",
                "summary": "A test post generated by the E2E test pipeline.",
                "tags": ["test", "e2e", "pipeline"],
                "date": "2025-10-28",
                "authors": ["test-author-uuid-1", "test-author-uuid-2"],
            },
            "content": "# Test Pipeline Output\n\nThis validates the writer agent integration.",
        },
        profile_reads=[
            {"author_uuid": "test-author-uuid-1"},
            {"author_uuid": "test-author-uuid-2"},
        ],
        profile_writes=[
            {
                "author_uuid": "test-author-uuid-1",
                "content": """# Profile: test-author-uuid-1

## Communication Style
Direct and test-focused. Primary conversation driver.

## Topics of Interest
Testing, system validation, quality assurance.
""",
            },
            {
                "author_uuid": "test-author-uuid-2",
                "content": """# Profile: test-author-uuid-2

## Communication Style
Responsive and collaborative. Supports testing efforts.

## Topics of Interest
System behavior, validation results.
""",
            },
        ],
        rag_searches=[
            {
                "query": "test pipeline validation",
                "media_types": ["images"],
                "limit": 3,
                "results": [
                    {
                        "document_id": "test-media-1",
                        "filename": "media/images/test-media-1.jpg",
                        "similarity": 0.92,
                        "caption": "Test execution screenshot",
                    }
                ],
            }
        ],
        annotations=[
            {
                "parent_id": "msg_test_001",
                "parent_type": "message",
                "commentary": "This message establishes the test context",
            }
        ],
        banners=[
            {
                "title": "Test Pipeline Output",
                "author_uuid": "test-author-uuid-1",
                "context": "E2E testing validation",
                "result": {
                    "banner_path": "posts/images/test-banner.jpg",
                    "alt_text": "Banner for test post",
                    "status": "generated",
                },
            }
        ],
    )


def get_mock_profile_content(author_uuid: str) -> str | None:
    """Get mock profile content for a given author UUID.

    Args:
        author_uuid: The author's UUID

    Returns:
        Profile content as markdown string, or None if not found
    """
    tool_seq = get_fixture_tool_sequence()
    profiles = {p["author_uuid"]: p["content"] for p in tool_seq.profile_writes}
    return profiles.get(author_uuid)
