tenets:
  no-compat: "No backwards compatibility layers or shims."
  clean: "Code must be simple, readable, and minimal."
  no-defensive: "Do not guard against impossible states; rely on types/tests."
  propagate-errors: "Do not swallow errors; let them bubble to boundaries."
