input_dir: ./input
output_dir: ./output

llm:
  model: models/gemini-2.5-flash
  temperature: 0.7
  max_retries: 3

curator:
  enabled: true
  min_message_length: 15
  cluster_threshold: 0.7
  max_topics_per_day: 10

enricher:
  enabled: true
  max_enrichments_per_post: 5
  enable_rag: false
  enable_web: false

writer:
  enabled: true
  language: pt-BR
  max_post_length: 5000

profiler:
  enabled: false
  min_messages: 10
