# Configuração padrão do Egregora usada em desenvolvimento e CI.
# Ajuste os caminhos conforme necessário para o seu ambiente local.

[directories]
zips_dir = "data/whatsapp_zips"
posts_dir = "data"

[rag]
enabled = true
embedding_model = "models/gemini-embedding-001"
export_embeddings = true
embedding_export_path = "artifacts/embeddings/post_chunks.parquet"
