# vulture_whitelist.py
# This file is used to whitelist false positives from Vulture.
# Items listed here are considered "used" even if static analysis thinks otherwise.
# Usage: vulture src tests vulture_whitelist.py

# --- CLI Commands (Registered via decorators) ---
init  # unused function (src/egregora/cli/main.py:68)
top  # unused function (src/egregora/cli/main.py:202)
show_reader_history  # unused function (src/egregora/cli/main.py:276)
doctor  # unused function (src/egregora/cli/main.py:362)

# --- Configuration & Pydantic (Dynamic access/Validation) ---
enable  # unused variable (src/egregora/agents/models.py:18)
ttl  # unused variable (src/egregora/agents/models.py:40)
inputs  # unused variable (src/egregora/agents/models.py:50)
contracts  # unused variable (src/egregora/agents/models.py:51)
model_config  # unused variable (src/egregora/config/settings.py:651)
min_similarity_threshold  # unused variable (src/egregora/config/settings.py:180)
embedding_max_batch_size  # unused variable (src/egregora/config/settings.py:192)
embedding_timeout  # unused variable (src/egregora/config/settings.py:198)
embedding_max_retries  # unused variable (src/egregora/config/settings.py:204)
anonymization_enabled  # unused variable (src/egregora/config/settings.py:246)
mkdocs_config_path  # unused variable (src/egregora/config/settings.py:469)
annotations_enabled  # unused variable (src/egregora/config/settings.py:531)
daily_llm_requests  # unused variable (src/egregora/config/settings.py:540)
nearby_messages  # unused variable (src/egregora/config/settings.py:956)
ocr_text  # unused variable (src/egregora/config/settings.py:957)
model_override  # unused variable (src/egregora/config/settings.py:928)
ranking  # unused variable (src/egregora/config/settings.py:95)
editor  # unused variable (src/egregora/config/settings.py:99)
model_rotation_enabled  # unused variable (src/egregora/config/settings.py:283)
rotation_models  # unused variable (src/egregora/config/settings.py:287)
HOURS  # unused variable (src/egregora/constants.py:20)
BYTES  # unused variable (src/egregora/constants.py:22)

# --- Validators ---
validate_pydantic_model_format  # unused method (src/egregora/config/settings.py:118)
validate_google_model_format  # unused method (src/egregora/config/settings.py:134)
validate_top_k  # unused method (src/egregora/config/settings.py:211)
validate_safe_path  # unused method (src/egregora/config/settings.py:430)
validate_cross_field  # unused method (src/egregora/config/settings.py:658)
from_cli_overrides  # unused method (src/egregora/config/settings.py:690)
from_cli_args  # unused method (src/egregora/config/settings.py:991)
get_openrouter_api_key  # unused function (src/egregora/config/settings.py:1041)
openrouter_api_key_status  # unused function (src/egregora/config/settings.py:1051)

# --- Agents & Tools ---
create_url_enrichment_agent  # unused function (src/egregora/agents/enricher.py:186)
_persist_enrichments  # unused function (src/egregora/agents/enricher.py:424)
_process_media_row  # unused function (src/egregora/agents/enricher.py:604)
Skill  # unused class (src/egregora/agents/registry.py:46)
resolve_toolset  # unused method (src/egregora/agents/registry.py:327)
get_toolset_hash  # unused method (src/egregora/agents/registry.py:350)
get_agent_hash  # unused method (src/egregora/agents/registry.py:379)
get_last_annotation_id  # unused method (src/egregora/agents/shared/annotations/__init__.py:306)
iter_annotation_documents  # unused method (src/egregora/agents/shared/annotations/__init__.py:325)
join_with_messages  # unused method (src/egregora/agents/shared/annotations/__init__.py:334)
ClusterInput  # unused class (src/egregora/agents/taxonomy.py:9)
WRITER_TEMPLATE_NAME  # unused variable (src/egregora/agents/writer.py:77)
DEFAULT_TEMPLATE_SIGNATURE  # unused variable (src/egregora/agents/writer.py:82)
LLMClient  # unused variable (src/egregora/agents/writer.py:96)
RagContext  # unused class (src/egregora/agents/writer.py:105)
_truncate_for_embedding  # unused function (src/egregora/agents/writer.py:146)
_extract_thinking_content  # unused function (src/egregora/agents/writer.py:232)
entry_type  # unused variable (src/egregora/agents/writer.py:254)
_prepare_deps  # unused function (src/egregora/agents/writer.py:435)
load_format_instructions  # unused function (src/egregora/agents/writer.py:999)
get_top_authors  # unused function (src/egregora/agents/writer.py:1015)
write_post_tool  # unused function (src/egregora/agents/writer_helpers.py:66)
read_profile_tool  # unused function (src/egregora/agents/writer_helpers.py:72)
write_profile_tool  # unused function (src/egregora/agents/writer_helpers.py:76)
annotate_conversation_tool  # unused function (src/egregora/agents/writer_helpers.py:80)
inject_rag_context  # unused function (src/egregora/agents/writer_setup.py:76)
inject_profiles_context  # unused function (src/egregora/agents/writer_setup.py:87)
caption  # unused variable (src/egregora/agents/writer_tools.py:60)
similarity  # unused variable (src/egregora/agents/writer_tools.py:70)

# --- Output Adapters ---
_initialized  # unused attribute (src/egregora/output_adapters/mkdocs/adapter.py:64)
get_markdown_extensions  # unused method (src/egregora/output_adapters/mkdocs/adapter.py:284)
_documents_from_dir  # unused method (src/egregora/output_adapters/mkdocs/adapter.py:524)
resolve_document_path  # unused method (src/egregora/output_adapters/mkdocs/adapter.py:547)
get_site_stats  # unused method (src/egregora/output_adapters/mkdocs/adapter.py:1062)
get_recent_media  # unused method (src/egregora/output_adapters/mkdocs/adapter.py:1154)
_append_author_cards  # unused method (src/egregora/output_adapters/mkdocs/adapter.py:1212)
_sync_author_profiles  # unused method (src/egregora/output_adapters/mkdocs/adapter.py:1464)
FILENAME_PARTS_WITH_EXTENSION  # unused variable (src/egregora/output_adapters/base.py:26)
additional_paths  # unused variable (src/egregora/output_adapters/base.py:47)
list_documents  # unused method (src/egregora/output_adapters/base.py:103)
posts_created  # unused variable (src/egregora/output_adapters/base.py:157)
base_path  # unused variable (src/egregora/data_primitives/protocols.py:43)
locale  # unused variable (src/egregora/data_primitives/protocols.py:44)

# --- Input Adapters ---
doc_url  # unused variable (src/egregora/input_adapters/base.py:83)
ir_version  # unused variable (src/egregora/input_adapters/base.py:84)
MEDIA_UUID_NAMESPACE  # unused variable (src/egregora/input_adapters/base.py:88)
_author_namespace  # unused attribute (src/egregora/input_adapters/whatsapp/adapter.py:52)
COMMAND_REGISTRY  # unused variable (src/egregora/input_adapters/whatsapp/commands.py:39)

# --- Database ---
write_table  # unused method (src/egregora/database/duckdb_manager.py:372)
drop_table  # unused method (src/egregora/database/duckdb_manager.py:671)
drop_index  # unused method (src/egregora/database/duckdb_manager.py:717)
row_count  # unused method (src/egregora/database/duckdb_manager.py:721)
get_latest_runs  # unused method (src/egregora/database/run_store.py:51)
get_run_by_id  # unused method (src/egregora/database/run_store.py:70)

# --- Ops & Utils ---
replace_media_mentions  # unused function (src/egregora/ops/media.py:187)
adapter_kwargs  # unused variable (src/egregora/ops/media.py:287)
save_media_asset  # unused function (src/egregora/ops/media.py:398)
parse_frontmatter_file  # unused function (src/egregora/markdown/frontmatter.py:43)
submitted_at  # unused variable (src/egregora/rag/embedding_router.py:178)
RAG  # unused variable (src/egregora/utils/cache.py:144)
write_markdown_post  # unused function (src/egregora/utils/filesystem.py:133)
sync_authors_from_posts  # unused function (src/egregora/utils/filesystem.py:189)
create_context  # unused method (src/egregora/orchestration/factory.py:45)

# --- Tests ---
mock_ensure_mkdocs  # unused variable (tests/unit/orchestration/pipelines/test_write_entrypoint.py:20)
mock_validate_key  # unused variable (tests/unit/orchestration/pipelines/test_write_entrypoint.py:20)
_ibis_backend  # unused function (tests/conftest.py:31)
whatsapp_timezone  # unused function (tests/conftest.py:102)
stub_enrichment_agents  # unused function (tests/conftest.py:112)
_stub_url_run  # unused function (tests/conftest.py:122)
_stub_media_run  # unused function (tests/conftest.py:125)
mime_hint  # unused variable (tests/conftest.py:142)
mock_embedding_model  # unused function (tests/conftest.py:185)
enrichment_test_config  # unused function (tests/conftest.py:266)
pipeline_test_config  # unused function (tests/conftest.py:283)
minimal_config  # unused function (tests/conftest.py:356)
daily_llm_requests  # unused attribute (tests/conftest.py:381)
clean_env  # unused function (tests/e2e/conftest.py:24)
temp_site_dir  # unused function (tests/e2e/conftest.py:76)
window_configs  # unused function (tests/e2e/conftest.py:112)
async_mock_url_enrichment  # unused function (tests/e2e/mocks/enrichment_mocks.py:86)
async_mock_media_enrichment  # unused function (tests/e2e/mocks/enrichment_mocks.py:104)
to_tool_call  # unused method (tests/e2e/mocks/llm_responses.py:71)
FIXTURE_WRITER_POST  # unused variable (tests/e2e/mocks/llm_responses.py:150)
MOCK_METADATA  # unused variable (tests/e2e/mocks/llm_responses.py:176)
DEFAULT  # unused variable (tests/e2e/test_config.py:23)
SLOW  # unused variable (tests/e2e/test_config.py:24)
FAST  # unused variable (tests/e2e/test_config.py:25)
INVALID_FORMAT_1  # unused variable (tests/e2e/test_config.py:34)
DAYS_1  # unused variable (tests/e2e/test_config.py:42)
DAYS_7  # unused variable (tests/e2e/test_config.py:43)
HOURS_24  # unused variable (tests/e2e/test_config.py:44)
MESSAGES_100  # unused variable (tests/e2e/test_config.py:45)
default_write_args  # unused function (tests/e2e/test_config.py:78)
assert_directory_exists  # unused function (tests/e2e/test_config.py:183)
create_writer_quality_dataset_with_judges  # unused function (tests/evals/writer_evals.py:110)
serve  # unused method (tests/helpers/storage.py:163)
get_by_label  # unused method (tests/helpers/storage.py:208)
write_url_enrichment  # unused method (tests/helpers/storage.py:261)
write_media_enrichment  # unused method (tests/helpers/storage.py:282)
get_url_enrichment_by_url  # unused method (tests/helpers/storage.py:296)
get_media_enrichment  # unused method (tests/helpers/storage.py:312)
init_kwargs  # unused attribute (tests/unit/agents/banner/test_banner_image_generation.py:13)
file  # unused variable (tests/unit/agents/banner/test_gemini_provider.py:20)
ANY  # unused import (tests/unit/agents/test_enricher_staging.py:3)
_relative_path_from_url  # unused function (tests/unit/output_adapters/mkdocs/test_url_convention.py:10)
_served_path_from_url  # unused function (tests/unit/output_adapters/mkdocs/test_url_convention.py:34)
_stub_agent_setup  # unused function (tests/utils/pydantic_test_models.py:60)
workspace_id  # unused attribute (tests/v3/core/test_context.py:48)
item_id  # unused variable (tests/v3/core/test_ports.py:38)
process  # unused method (tests/v3/core/test_ports.py:46)

# --- V3 Code (Protected from deletion) ---
model_config  # unused variable (src/egregora_v3/core/catalog.py:31)
fallback_model  # unused variable (src/egregora_v3/core/config.py:18)
abs_profiles_dir  # unused property (src/egregora_v3/core/config.py:47)
abs_media_dir  # unused property (src/egregora_v3/core/config.py:51)
abs_lancedb_path  # unused property (src/egregora_v3/core/config.py:59)
model_config  # unused variable (src/egregora_v3/core/config.py:88)
workspace_id  # unused variable (src/egregora_v3/core/context.py:34)
MediaStore  # unused class (src/egregora_v3/core/ports.py:32)
create_document  # unused method (src/egregora_v3/core/ports.py:46)
collection_id  # unused variable (src/egregora_v3/core/ports.py:46)
update_document  # unused method (src/egregora_v3/core/ports.py:47)
list_documents  # unused method (src/egregora_v3/core/ports.py:48)
collection_id  # unused variable (src/egregora_v3/core/ports.py:50)
WorkspaceServiceWithMedia  # unused class (src/egregora_v3/core/ports.py:55)
upload_media_document  # unused method (src/egregora_v3/core/ports.py:59)
collection_id  # unused variable (src/egregora_v3/core/ports.py:61)
LLMModel  # unused class (src/egregora_v3/core/ports.py:89)
process  # unused method (src/egregora_v3/core/ports.py:109)
contributors  # unused variable (src/egregora_v3/core/types.py:59)
extensions  # unused variable (src/egregora_v3/core/types.py:72)
PLAN  # unused variable (src/egregora_v3/core/types.py:84)
CONCEPT  # unused variable (src/egregora_v3/core/types.py:89)
ARCHIVED  # unused variable (src/egregora_v3/core/types.py:95)
custom_system_prompt  # unused attribute (src/egregora_v3/engine/agents/enricher.py:53)
TOOLS  # unused variable (src/egregora_v3/engine/tools.py:157)
ATOM_NSMAP  # unused variable (src/egregora_v3/infra/adapters/rss.py:25)
exc_type  # unused variable (src/egregora_v3/infra/adapters/rss.py:62)
exc_val  # unused variable (src/egregora_v3/infra/adapters/rss.py:63)
exc_tb  # unused variable (src/egregora_v3/infra/adapters/rss.py:64)
_manual_upsert  # unused method (src/egregora_v3/infra/repository/duckdb.py:80)
document_json  # unused variable (src/egregora_v3/infra/vector/lancedb.py:38)
PERSON  # unused variable (src/egregora_v3/knowledge/concepts.py:19)
PLACE  # unused variable (src/egregora_v3/knowledge/concepts.py:20)
EVENT  # unused variable (src/egregora_v3/knowledge/concepts.py:21)
ARTIFACT  # unused variable (src/egregora_v3/knowledge/concepts.py:22)
TERM  # unused variable (src/egregora_v3/knowledge/concepts.py:23)
MEME  # unused variable (src/egregora_v3/knowledge/concepts.py:24)
OTHER  # unused variable (src/egregora_v3/knowledge/concepts.py:25)
target_slug  # unused variable (src/egregora_v3/knowledge/concepts.py:30)
relation_type  # unused variable (src/egregora_v3/knowledge/concepts.py:31)
ConceptExtraction  # unused class (src/egregora_v3/knowledge/concepts.py:35)
related_slugs  # unused variable (src/egregora_v3/knowledge/concepts.py:40)
WikiPage  # unused class (src/egregora_v3/knowledge/concepts.py:44)
create_concept  # unused method (src/egregora_v3/knowledge/concepts.py:57)
