name: Shared Gemini Runner
description: Run Gemini with a fallback model list and standardized outputs.

inputs:
  prompt:
    description: Prompt to send to Gemini.
    required: true
  fallback_models:
    description: JSON array or single Gemini model ID (first entry is used).
    required: true
  gemini_api_key:
    description: API key used to call Gemini.
    required: true

outputs:
  summary:
    description: Gemini response summary from the first successful model.
    value: ${{ steps.select.outputs.summary }}
  outcome:
    description: Outcome of the Gemini run (success or failure).
    value: ${{ steps.select.outputs.outcome }}
  model:
    description: Model that produced the selected summary.
    value: ${{ steps.select.outputs.model }}
  diagnostics:
    description: Human-readable attempt log for troubleshooting.
    value: ${{ steps.select.outputs.diagnostics }}
  attempts:
    description: JSON array of attempted models in order.
    value: ${{ steps.select.outputs.attempts }}

runs:
  using: composite
  steps:
    - name: Parse fallback models
      id: models
      shell: bash
      env:
        FALLBACK_MODELS: ${{ inputs.fallback_models }}
      run: |
        set -euo pipefail

        python - <<'PY' > /tmp/models
          import json
          import os
          import sys

          raw = os.environ.get("FALLBACK_MODELS", "").strip()
          models = []

          if not raw:
              sys.exit("fallback_models must specify at least one model")

          try:
              parsed = json.loads(raw)
          except json.JSONDecodeError:
              models = [raw]
          else:  # pragma: no cover - executed in workflow only
              if isinstance(parsed, list):
                  models = [str(value).strip() for value in parsed if str(value).strip()]
              elif isinstance(parsed, str):
                  models = [parsed.strip()]
              else:
                  sys.exit("fallback_models must be a JSON array or string")

          if not models:
              sys.exit("fallback_models must specify at least one model")

          primary = models[0]
          print(f"primary_model={primary}")
          print(f"attempts_json={json.dumps(models)}")
        PY

        cat /tmp/models >> "$GITHUB_OUTPUT"

    - name: Run Gemini
      id: gemini_primary
      uses: google-github-actions/run-gemini-cli@v0
      continue-on-error: true
      with:
        gemini_api_key: ${{ inputs.gemini_api_key }}
        gemini_model: ${{ steps.models.outputs.primary_model }}
        prompt: ${{ inputs.prompt }}

    - name: Select Gemini result
      id: select
      shell: bash
      env:
        PRIMARY_OUTCOME: ${{ steps.gemini_primary.outcome }}
        PRIMARY_SUMMARY: ${{ steps.gemini_primary.outputs.summary }}
        PRIMARY_MODEL: ${{ steps.models.outputs.primary_model }}
        ATTEMPTS_JSON: ${{ steps.models.outputs.attempts_json }}
      run: |
        set -euo pipefail

        final_outcome="${PRIMARY_OUTCOME:-failure}"
        final_summary="${PRIMARY_SUMMARY:-}"
        final_model="${PRIMARY_MODEL:-}"

        if [ -z "$final_summary" ]; then
          final_summary="Gemini did not return a response."
        fi

        diagnostics=("Attempt (${PRIMARY_MODEL:-unset}): ${PRIMARY_OUTCOME:-unknown}")

        {
          echo "summary<<'EOF'"
          echo "$final_summary"
          echo "EOF"
          echo "outcome=$final_outcome"
          echo "model=$final_model"
          echo "diagnostics=${diagnostics[*]}"
          echo "attempts=$ATTEMPTS_JSON"
        } >> "$GITHUB_OUTPUT"
