"""Golden-fixture test that exercises the WhatsApp pipeline through the new
Pydantic-AI writer backend.

Rather than replaying previously recorded Gemini HTTP traffic, we stub the
`GeminiModel` with `pydantic_ai.models.test.TestModel`, which deterministically
calls the writer tools and returns structured output. This keeps the test fast,
deterministic, and completely offline while still validating that the Pydantic
agent orchestrates file generation end-to-end.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest
from pydantic_ai.models.test import TestModel

from egregora.output_adapters.mkdocs import resolve_site_paths
from egregora.orchestration.write_pipeline import (
    WhatsAppProcessOptions,
    process_whatsapp_export,
)
from tests.utils.mock_batch_client import create_mock_genai_client

if TYPE_CHECKING:
    from pathlib import Path


@pytest.mark.xfail(
    reason="Test needs refactoring for pydantic-ai Agent pattern - monkeypatching GeminiModel no longer works"
)
def test_pipeline_with_golden_fixtures(
    whatsapp_fixture,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Run the full pipeline using the deterministic Pydantic-AI writer agent."""
    output_dir = tmp_path / "site"
    output_dir.mkdir()

    # Create mkdocs.yml for site structure
    mkdocs_yml = output_dir / "mkdocs.yml"
    mkdocs_yml.write_text("site_name: Test Site\ndocs_dir: docs\n", encoding="utf-8")

    docs_dir = output_dir / "docs"
    docs_dir.mkdir()

    # Force the writer to use the Pydantic backend with deterministic tooling.
    monkeypatch.setenv("EGREGORA_LLM_BACKEND", "pydantic")

    class GoldenTestModel(TestModel):
        """TestModel variant with scripted tool arguments for deterministic output."""

        def __init__(self, *, window_id: str):
            self._window_id = window_id
            super().__init__(
                call_tools=["write_post_tool", "write_profile_tool"],
                custom_output_args={
                    "summary": "Golden fixtures generated",
                    "notes": "Deterministic TestModel",
                },
                seed=7,
            )

        def gen_tool_args(self, tool_def):  # type: ignore[override]
            if tool_def.name == "write_post_tool":
                return {
                    "metadata": {
                        "title": "Deterministic Insights",
                        "slug": "deterministic-insights",
                        "date": self._window_id,
                        "tags": ["deterministic", "test"],
                        "authors": ["ca71a986"],
                        "summary": "Synthetic summary generated for golden fixture validation.",
                    },
                    "content": (
                        "# Deterministic Post\n\n"
                        "This content is emitted by GoldenTestModel to keep the pipeline test stable."
                    ),
                }
            if tool_def.name == "write_profile_tool":
                return {
                    "author_uuid": "ca71a986",
                    "content": (
                        "Profile content generated by GoldenTestModel "
                        "to ensure the writer records profile updates."
                    ),
                }
            return super().gen_tool_args(tool_def)

    def _make_test_model(model_name: str) -> TestModel:
        # Period date is derived from the WhatsApp export metadata.
        return GoldenTestModel(window_id=whatsapp_fixture.export_date.isoformat())

    monkeypatch.setattr(
        "egregora.agents.writer.agent.GeminiModel",
        _make_test_model,
    )

    client = create_mock_genai_client()

    # Run the pipeline - enrichment remains disabled because we do not stub binary uploads here.
    options = WhatsAppProcessOptions(
        output_dir=output_dir,
        step_size=100,
        step_unit="messages",
        overlap_ratio=0.2,
        enable_enrichment=False,  # Binary uploads remain hard to stub in this test harness
        retrieval_mode="exact",  # Exact mode avoids VSS extension dependency (see docstring)
        client=client,
    )
    process_whatsapp_export(
        whatsapp_fixture.zip_path,
        options=options,
    )

    # Verify that the basic output structure was created
    site_paths = resolve_site_paths(output_dir)
    posts_dir = site_paths.posts_dir
    assert posts_dir.exists(), "Posts directory should be created"

    profiles_dir = site_paths.profiles_dir
    assert profiles_dir.exists(), "Profiles directory should be created"

    # Verify the site contains markdown artifacts (scaffolding + generated files)
    markdown_files = list(docs_dir.rglob("*.md"))
    assert markdown_files, "Expected markdown content to be generated"
