from __future__ import annotations

from typing import Any

class RankingStore:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get_comments_for_post(self, post_id: str) -> Any: ...
    def save_comparison(self, data: Any) -> None: ...
    def get_rating(self, post_id: str) -> Any: ...
    def update_ratings(self, post_a: str, post_b: str, new_a: float, new_b: float) -> None: ...
