
from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from egregora.data_primitives.document import Document, DocumentType

if TYPE_CHECKING:
    from egregora.agents.types import WriterDeps

logger = logging.getLogger(__name__)

def _execute_mock_writer(
    deps: WriterDeps,
) -> tuple[list[str], list[str]]:
    """Execute writer in mock mode."""
    logger.info("MOCK MODE: Generating placeholder post without LLM.")

    slug = f"{deps.window_start.strftime('%Y-%m-%d')}-mock-post"
    content = f"""# Mock Post {deps.window_start.strftime('%Y-%m-%d')}

This is a placeholder post generated by the mock writer.

## Summary
Auto-generated content for testing purposes.

## Content
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
"""
    doc = Document(
        content=content,
        type=DocumentType.POST,
        metadata={
            "slug": slug,
            "date": deps.window_start.strftime("%Y-%m-%d"),
            "title": f"Mock Post {deps.window_start.strftime('%Y-%m-%d')}",
        },
        source_window=deps.window_label,
    )

    deps.resources.output.persist(doc)
    return [doc.document_id], []
