from __future__ import annotations

from typing import Any, Sequence

class Table:
    columns: Sequence[str]

    def count(self) -> Any: ...
    def execute(self) -> Any: ...
    def filter(self, *args: Any, **kwargs: Any) -> Table: ...
    def order_by(self, *args: Any, **kwargs: Any) -> Table: ...
    def union(self, other: Table, distinct: bool = ...) -> Table: ...
    def mutate(self, **kwargs: Any) -> Table: ...
    def select(self, *args: Any, **kwargs: Any) -> Table: ...

    def __getattr__(self, name: str) -> Any: ...
