name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: "The dashboard shows incorrect tribunal coverage percentages..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run `uv run python scripts/pipeline/collect.py`
        2. Check dashboard at http://localhost:5173
        3. Observe incorrect percentage
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "Coverage should show 15.2% based on DuckDB query..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Dashboard shows 0.8% instead..."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Provide relevant environment details:
        - OS (Linux, macOS, Windows)
        - Python version (`python --version`)
        - uv version (`uv --version`)
        - DuckDB version (if relevant)
      placeholder: |
        - OS: Ubuntu 22.04
        - Python: 3.12.1
        - uv: 0.1.0
      render: markdown
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs or Screenshots
      description: |
        Paste logs, error messages, or attach screenshots.
        Tip: You can drag and drop images here!
      placeholder: |
        ```
        ERROR: DuckDB connection failed at collect.py:145
        ```
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have included all relevant details (steps, environment, logs)
          required: true
        - label: This issue is specific to causaganha (not a general Python/DuckDB question)
          required: true
