from typing import Any, Iterable

class Progress:
    def __enter__(self) -> "Progress": ...
    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: Any | None) -> None: ...

class TaskID(int):
    ...

def track(sequence: Iterable[Any], *args: Any, **kwargs: Any) -> Iterable[Any]: ...
