"""Centralized configuration for Egregora.

DEPRECATED: This module is a compatibility shim for V3 infrastructure.
"""

from __future__ import annotations

from egregora_v3.core.config import (
    DEFAULT_BANNER_MODEL,
    DEFAULT_EMBEDDING_MODEL,
    DEFAULT_MODEL,
    DEFAULT_PIPELINE_DB,
    DEFAULT_RUNS_DB,
    EMBEDDING_DIM,
    EgregoraConfig,
    EnrichmentRuntimeConfig,
    EnrichmentSettings,
    FeaturesSettings,
    MediaEnrichmentContext,
    ModelSettings,
    ModelType,
    OutputSettings,
    PathsSettings,
    PipelineEnrichmentConfig,
    PipelineSettings,
    PrivacySettings,
    RAGSettings,
    ReaderSettings,
    RuntimeContext,
    WriterAgentSettings,
    WriterRuntimeConfig,
    create_default_config,
    find_egregora_config,
    load_egregora_config,
    save_egregora_config,
    get_openrouter_api_key,
    openrouter_api_key_status,
)

__all__ = [
    "DEFAULT_BANNER_MODEL",
    "DEFAULT_EMBEDDING_MODEL",
    "DEFAULT_MODEL",
    "DEFAULT_PIPELINE_DB",
    "DEFAULT_RUNS_DB",
    "EMBEDDING_DIM",
    "EgregoraConfig",
    "EnrichmentRuntimeConfig",
    "EnrichmentSettings",
    "FeaturesSettings",
    "MediaEnrichmentContext",
    "ModelSettings",
    "ModelType",
    "OutputSettings",
    "PathsSettings",
    "PipelineEnrichmentConfig",
    "PipelineSettings",
    "PrivacySettings",
    "RAGSettings",
    "ReaderSettings",
    "RuntimeContext",
    "WriterAgentSettings",
    "WriterRuntimeConfig",
    "create_default_config",
    "find_egregora_config",
    "load_egregora_config",
    "save_egregora_config",
    "get_openrouter_api_key",
    "openrouter_api_key_status",
]
