name: "Setup Python with uv"
description: "Install uv/Python and sync dependencies with automatic fallback"
inputs:
  python-version:
    description: "Python version to install"
    default: "3.12"
    required: false
  extras:
    description: "Arguments passed to `uv sync`"
    default: "--all-extras"
    required: false
runs:
  using: "composite"
  steps:
    - name: Install uv (primary)
      id: setup_uv
      uses: astral-sh/setup-uv@v5
      continue-on-error: true
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python with uv (primary)
      if: steps.setup_uv.outcome == 'success'
      shell: bash
      run: uv python install ${{ inputs.python-version }}

    - name: Install dependencies with uv (primary)
      if: steps.setup_uv.outcome == 'success'
      shell: bash
      run: uv sync ${{ inputs.extras }}

    - name: Set up Python (fallback)
      if: steps.setup_uv.outcome != 'success'
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Install uv via pip (fallback)
      if: steps.setup_uv.outcome != 'success'
      shell: bash
      run: pip install uv

    - name: Install dependencies with uv (fallback)
      if: steps.setup_uv.outcome != 'success'
      shell: bash
      run: uv sync ${{ inputs.extras }}
