name: Request Codex Review

on:
  pull_request_target:
    types:
      - opened

permissions:
  pull-requests: write
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on new pull request
        env:
          GH_TOKEN: ${{ secrets.CODEX_REVIEW_TOKEN }}
        run: |
          gh api \
            repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
            -f body='@codex code review'
