name: Sync Dev Issues

on:
  workflow_dispatch:
  schedule:
    - cron: '15 * * * *'
  push:
    branches:
      - main
    paths:
      - 'dev/issues/**'
      - '.github/workflows/sync-dev-issues.yml'
  issues:
    types: [opened, edited, closed, reopened]

permissions:
  contents: write
  issues: write

jobs:
  sync:
    if: github.event_name != 'push' || github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch || github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Synchronize dev/issues with GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/issue_sync.py --repo "${{ github.repository }}"

      - name: Commit synchronized files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: sync dev issues'
          file_pattern: dev/issues/**/*.md
